"""empty message

Revision ID: 48c728d592f
Revises: 3e2aa6cdb2d
Create Date: 2015-03-05 15:30:46.896289

"""

# revision identifiers, used by Alembic.
revision = '48c728d592f'
down_revision = '3e2aa6cdb2d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
